### ISSUE TITLE
compare_conj_pre.txt - NONE entries

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/elispsanskrit#49]
When I reran the code locally in my  machine,
some of it gave None. A bit wierd. Please look into it. Maybe because of something related to generatedforms.xml ?

None pre 10A: conjugation differences @ 3s,3d,3p,2s,2d,2p,1s,1d,1p 
     3s (sanverb) BaYjayate,DAvayate,DUnayate,DrAsayate,Iqayate,Irayate,aYjayate,capayate,cayayate,cowayate,dAsayate,darBayate,elayate,jArayate,jAsayate,jYApayate,kopayate,medayate,peSayate,powayate,qepayate,tApayate,tarpayate,trowayate,varjayate,vartayate != Noneayate (pysan)
     3d (sanverb) BaYjayete,DAvayete,DUnayete,DrAsayete,Iqayete,Irayete,aYjayete,capayete,cayayete,cowayete,dAsayete,darBayete,elayete,jArayete,jAsayete,jYApayete,kopayete,medayete,peSayete,powayete,qepayete,tApayete,tarpayete,trowayete,varjayete,vartayete != Noneayete (pysan)
     3p (sanverb) BaYjayante,DAvayante,DUnayante,DrAsayante,Iqayante,Irayante,aYjayante,capayante,cayayante,cowayante,dAsayante,darBayante,elayante,jArayante,jAsayante,jYApayante,kopayante,medayante,peSayante,powayante,qepayante,tApayante,tarpayante,trowayante,varjayante,vartayante != Noneayante (pysan)
     2s (sanverb) BaYjayase,DAvayase,DUnayase,DrAsayase,Iqayase,Irayase,aYjayase,capayase,cayayase,cowayase,dAsayase,darBayase,elayase,jArayase,jAsayase,jYApayase,kopayase,medayase,peSayase,powayase,qepayase,tApayase,tarpayase,trowayase,varjayase,vartayase != Noneayase (pysan)
     2d (sanverb) BaYjayeTe,DAvayeTe,DUnayeTe,DrAsayeTe,IqayeTe,IrayeTe,aYjayeTe,capayeTe,cayayeTe,cowayeTe,dAsayeTe,darBayeTe,elayeTe,jArayeTe,jAsayeTe,jYApayeTe,kopayeTe,medayeTe,peSayeTe,powayeTe,qepayeTe,tApayeTe,tarpayeTe,trowayeTe,varjayeTe,vartayeTe != NoneayeTe (pysan)
     2p (sanverb) BaYjayaDve,DAvayaDve,DUnayaDve,DrAsayaDve,IqayaDve,IrayaDve,aYjayaDve,capayaDve,cayayaDve,cowayaDve,dAsayaDve,darBayaDve,elayaDve,jArayaDve,jAsayaDve,jYApayaDve,kopayaDve,medayaDve,peSayaDve,powayaDve,qepayaDve,tApayaDve,tarpayaDve,trowayaDve,varjayaDve,vartayaDve != NoneayaDve (pysan)
     1s (sanverb) BaYjaye,DAvaye,DUnaye,DrAsaye,Iqaye,Iraye,aYjaye,capaye,cayaye,cowaye,dAsaye,darBaye,elaye,jAraye,jAsaye,jYApaye,kopaye,medaye,peSaye,powaye,qepaye,tApaye,tarpaye,trowaye,varjaye,vartaye != Noneaye (pysan)
     1d (sanverb) BaYjayAvahe,DAvayAvahe,DUnayAvahe,DrAsayAvahe,IqayAvahe,IrayAvahe,aYjayAvahe,capayAvahe,cayayAvahe,cowayAvahe,dAsayAvahe,darBayAvahe,elayAvahe,jArayAvahe,jAsayAvahe,jYApayAvahe,kopayAvahe,medayAvahe,peSayAvahe,powayAvahe,qepayAvahe,tApayAvahe,tarpayAvahe,trowayAvahe,varjayAvahe,vartayAvahe != NoneayAvahe (pysan)
     1p (sanverb) BaYjayAmahe,DAvayAmahe,DUnayAmahe,DrAsayAmahe,IqayAmahe,IrayAmahe,aYjayAmahe,capayAmahe,cayayAmahe,cowayAmahe,dAsayAmahe,darBayAmahe,elayAmahe,jArayAmahe,jAsayAmahe,jYApayAmahe,kopayAmahe,medayAmahe,peSayAmahe,powayAmahe,qepayAmahe,tApayAmahe,tarpayAmahe,trowayAmahe,varjayAmahe,vartayAmahe != NoneayAmahe (pysan)

**Comment by funderburkjim** [comment]
I noticed this too, before I read your comment here.  See
[SanskritVerb Issue 973](https://github.com/drdhaval2785/SanskritVerb/issues/973).

**Comment by funderburkjim** [comment]
I will wait until this resolved in SanskritVerb before doing another local regeneration and updating the
comparisons.   Then, I'll go back to previous issues to be sure I've implemented all the additional corrections to pysanskrit that you've pointed out (e.g., for gA).

**Comment by drdhaval2785** [comment]
Sure. You will get updated wrongformfinder.sh today evening.

**Comment by drdhaval2785** [comment]
This issue is resolved. Now both are in sync.
script listgen.php in scripts folder does the regeneration.
`php listgen.php` takes $verbdata (from verbdata.php itself) as input and regenerates 
 the `scripts/verbdata.php` and `Data/list1.txt` files.
